scripts/upload-data.js
* add a schema defining the data for each of the files
* check the existence and type of each field
=> feat: add schema checking to data before upload

src/components/base/ExternalLink.vue, src/views/AboutPage.vue, src/views/datasets/vaccine-gap/dashboard.vue
Could use some advice on styling for the more info section. I thought about making the "I can..." parts somewhat larger, but didn't know the best way to do so (I thought of a couple ways I *could* but wasn't sure if it was the best way.)
=> refactor: update text for more information

src/assets/styles/main.scss, src/components/base/HiddenContent.vue, src/components/dashboard/GapByRace.vue, src/components/dashboard/PotentialBarriers.vue, src/views/datasets/vaccine-gap/dashboard.vue
- Potential barriers side by side formatting
❓ What side was the table supposed to be on? I have forgotten
❓ Do we have the state data?
=> refactor: styling of potential barriers

src/views/datasets/vaccine-gap/dashboard.vue
Add in text above map to explain dashed areas
=> refactor: add map dash text

scripts/README.md, scripts/upload-data.js, src/components/dashboard/PotentialBarriers.vue, src/env.d.ts, src/utils/firebase.ts, src/views/datasets/vaccine-gap/dashboard.vue
- Adds state barriers file to the upload script
- Uses state barriers stats in the potential barriers section
=> feat: state barriers file

src/components/dashboard/PotentialBarriers.vue
Slightly tweaked barrier language to reflect RIDOH feedback
=> Update barrier language

src/components/dashboard/ControlPanel.vue, src/composables/useQueryParam.ts, src/router.ts, src/views/datasets/vaccine-gap/dashboard.vue, src/views/datasets/vaccine-gap/index.vue
* Add query params for
* date
* active cluster
* town
* stat
* zoomed
* Keep these in sync with the `ref` variables in the dashboard
* When date or town changes, reset cluster and zoom
* When we're showing old data, add a quick link to see the latest data
=> Feat: query params

src/components/base/ExternalLink.vue, src/views/AboutPage.vue
=> refactor: make social media launch in new tab

src/components/base/SideBar.vue, src/components/dashboard/GapByRace.vue, src/components/dashboard/PotentialBarriers.vue, src/router.ts, src/views/datasets/booster-gap/dashboard.vue, src/views/datasets/booster-gap/index.vue, src/views/datasets/vaccine-gap/dashboard.vue
Adds a page for the booster gaps
=> refactor: add booster page

scripts/README.md
Best way to look at this PR is by going to files changes and viewing the file.
=> docs: in depth tutorial

src/components/dashboard/ClusterMap.vue, src/components/dashboard/ColdMap.vue, src/utils/utils.ts
- Increases shape details for the overall map (slightly) and even more so for when you zoom into the map
closes #59
=> refactor: more shape details for map

package-lock.json, src/components/dashboard/DataNotes.vue, src/views/datasets/booster-gap/dashboard.vue, src/views/datasets/vaccine-gap/dashboard.vue
=> Add component for data notes

src/components/dashboard/VaccineResources.vue, src/views/datasets/booster-gap/dashboard.vue, src/views/datasets/vaccine-gap/dashboard.vue
=> refactor: make VaccineResources component

src/components/base/SideBar.vue
Add data spotlights to sidebar
=> Sidebar spotlights

src/views/datasets/booster-gap/dashboard.vue, src/views/datasets/vaccine-gap/dashboard.vue
Change zoom button color to green so it's more obvious to users
=> refactor: change zoom button color

src/components/dashboard/DataNotes.vue, src/components/dashboard/VaccineResources.vue, src/views/datasets/booster-gap/dashboard.vue, src/views/datasets/vaccine-gap/dashboard.vue
Change some text from RIDOH's notes
=> updates from RIDOH's review

src/components/dashboard/ColdMap.vue, src/views/datasets/booster-gap/dashboard.vue, src/views/datasets/vaccine-gap/dashboard.vue
=> feat: update tooltip, and uppercase dropdown

src/components/dashboard/GapByRace.vue, src/views/datasets/booster-gap/dashboard.vue, src/views/datasets/vaccine-gap/dashboard.vue
=> feat: add all residents

src/router.ts, src/views/datasets/booster-gap/dashboard.vue, src/views/datasets/vaccine-gap/dashboard.vue
Creates arrows to entice users to keep scrolling
Closes #155
=> Scroll down

src/views/datasets/booster-gap/index.vue, src/views/datasets/vaccine-gap/index.vue
=> fix: make 'view latest data' reset to full map view

src/components/dashboard/GapChart.vue
=> feat: add gap chart labels

package-lock.json, package.json, scripts/upload-housing.js
- added `csv-parse`
- updated the usage of `parse`
=> fix: csv parse

package-lock.json, package.json, scripts/upload-housing.js
Changes to upload spotlight as CSV instead of JSON
=> Upload spotlight as csv

src/components/dashboard/ColdMap.vue, src/utils/constants.ts, src/views/datasets/booster-gap/dashboard.vue, src/views/datasets/vaccine-gap/dashboard.vue
This allows flexibility in what color scale to use for the cold map so that it can also be a hot map.
=> feat: allow different color scales to be used in cold map

src/views/datasets/booster-gap/dashboard.vue
Only show "Bivalent" text if the date is on or after 3/15/2023
=> change bivalent text based on date

scripts/upload-data.js
=> fix: change vaccine to vax

src/views/spotlights/housing/dashboard.vue
Removed duplicate dropdown definition.
- Fixes #196
@s-bessey I think this is the fix you were talking about? If you wouldn't mind giving this a quick look to make sure, that would be wonderful 😄
=> fix: Dashboard dropdown cleanup

src/components/dashboard/HotspotCard.vue
I fixed the domain calculation for the rates
=> fix: hotspot chart domain
